// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "parseSource": string;
      "parseTier": string;
      "localApiBaseURL": string;
      "localApiTimeoutMinutes": number;
      "apiEnabled": boolean;
      "saveImages": boolean;
      "syncFolder": string;
      "autoParsePageLimit": number;
      "statusTags": boolean;
    };
  }
}
